### ISSUE TITLE
Split into multiple Podspecs

### ISSUE THREAD

**Issue by jlaws** [ennioma/arek#10]
Just referencing some code (Health stuff) even if you don't use it requires users to add special authorization to their PLIST.  You can get around this, and reduce your library size by splitting it into multiple targets like this [library](https://github.com/jlaws/JLPermissions/blob/master/JLPermissions.podspec).

**Comment by ennioma** [comment]
Thank you so much for this suggestion. It's brilliant.. and congrats for you library!

**Comment by ennioma** [comment]
Fixed with PR #23. Thanks!
