### ISSUE TITLE
Cannot convert value of type '(_) -> ()' to expected argument type '(() -> Void)?'

### ISSUE THREAD

**Issue by sirvon** [ennioma/arek#101]
I keep getting that error message upon any cocoapods install.

I am using Xcode 9.3 beta and swift 4, but I added
this to the podfile....

```ruby

post_install do |installer|
  # List of Pods to use as Swift 3.2
  myTargets = ['arek/Location']

  installer.pods_project.targets.each do |target|
    if myTargets.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
      end
  end

```

any hints on thoughts on what could be foul?

**Comment by ennioma** [comment]
Hi @sirvon,
sorry for the extremely late reply. I've released the version 1.7.1 that should solve that problem.

Let me know if it works for you!
