### ISSUE TITLE
ArekNotifications::status(completion:) not exhaustive

### ISSUE THREAD

**Issue by MatrixSenpai** [ennioma/arek#115]
ArekNotifications.swift `ArekNotifications::status(completion:)` for iOS 10.0 switch is not exhaustive

Need to add `case .provisional: return completion(.authorized)` or create a new `ArekPermissionResponse` to provide for `provisional` cases
(lines 43-53, `ArekNotifications.swift`)

IMO, you can just set it to authorized, it is on the user to check the status, and when `provisional` has been revoked, it should return to `.denied`

**Comment by jjjjjeffrey** [comment]
@MatrixSenpai you mean Xcode 10?

**Comment by MatrixSenpai** [comment]
That’s correct

**Comment by ennioma** [comment]
Hi @MatrixSenpai,
I've fixed it in a new branch released [here - 3.0.0](https://github.com/ennioma/arek/releases/tag/3.0.0)

For a while I'll keep open a new branch `iOS12` kept in sync with develop. Thanks for your contribution!

**Comment by MatrixSenpai** [comment]
@ennioma thanks for fixing this, will check out soon
My hackintosh has been down for a few weeks, finally got it back up so I should be able to test it out, but I'm going to guess it's good :)
