### ISSUE TITLE
iOS12 branch is unusable due to Swift4.2-incompatbile PMAlertController

### ISSUE THREAD

**Issue by robbiet480** [ennioma/arek#121]
Currently, PMAlertController is spewing a lot of errors during build on a Swift4.2 project due to Swift 4.2 changes. I've gotten around this by doing the following:

1. Removing the version requirement of the `s.dependency` in the Podspec
2. Installing PMAlertController via a [fork which has been updated for Swift4.2](https://github.com/pmusolino/PMAlertController/pull/71)
3. Configuring my Podfile like this so that arek has access to PMAlertController:
```ruby
pod 'PMAlertController', :git => 'https://github.com/gorbat-o/PMAlertController.git', :branch => 'swift4.2'
pod 'arek', :git => 'https://github.com/robbiet480/arek.git', :branch => 'iOS12'
```

**Comment by gorbat-o** [comment]
Hey, the pull request is created on PMAlertController :)
https://github.com/pmusolino/PMAlertController/pull/71

**Comment by ennioma** [comment]
Fixed, going to release it ;)

**Comment by ennioma** [comment]
@robbiet480, @gorbat-o please when you have time could you please check the release [https://github.com/ennioma/arek/releases/tag/4.0.0](4.0.0)?

**Comment by ennioma** [comment]
I forgot to submit the pod to Cocopods 🤦🏻‍♂️

**Comment by gorbat-o** [comment]
@ennioma hey
did you submit it ? 
I still have the error :/

**Comment by ennioma** [comment]
Yes! @gorbat-o try the version 4.0.1 please

**Comment by gorbat-o** [comment]
I might do something wrong I guess.. :/
Still not working :/

```
[!] CocoaPods could not find compatible versions for pod "arek/Contacts":
  In Podfile:
    arek/Contacts (= 4.0.1)

Specs satisfying the `arek/Contacts (= 4.0.1)` dependency were found, but they required a higher minimum deployment target.
```

Is the minimum deployment target changed ? :/

**Comment by ennioma** [comment]
Life is going fast ahead :P

**Comment by robbiet480** [comment]
@ennioma Was there a specific reason to set the deployment target to iOS 11? Most apps with large user bases support the last 2 major iOS versions. I'm gonna need to hack around with the Podspec to get this installed with a deployment target of iOS 10. It doesn't appear like there's anything that required the switch to 11 but I'm probably missing something.

**Comment by ennioma** [comment]
Hey @robbiet480 I've created the PR #127 only for the releases that will support Xcode 10. Let me know what you think

**Comment by ennioma** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  arek (4.0.2) successfully published
 📅  October 2nd, 23:07
 🌎  https://cocoapods.org/pods/arek
 👍  Tell your friends!
--------------------------------------------------------------------------------

And the release is [here](https://github.com/ennioma/arek/releases/tag/4.0.2) 🤙🏼
