### ISSUE TITLE
Install from pod

### ISSUE THREAD

**Issue by bourvill** [ennioma/arek#17]
Hi, 

I try to use your library via pod install.

i have problem, all classes are not available, visibility are not public class and can't be used outside your module itself.

(And why in your readme, you use EMClass ? What this ? Your class are named ArekPhoto, can you explain?)

Regards

**Comment by ennioma** [comment]
Hi @bourvill,
thank you a lot for this comment. I've fixed this with the PR #21.

Try the version 0.0.5 and let me know if everything is ok for you!

About the EM classes the reason for the wrong README is that previously I decided to name this class "EMPermission" but then I moved to Arek and I forgot to updated the README.

**Comment by bourvill** [comment]
Nice work and nice library.
Thank for your reactivity,

Regards

**Comment by ennioma** [comment]
You are welcome!

Let me know if now everything is fine for you ;)
