### ISSUE TITLE
When permissions denied, go to settings on request

### ISSUE THREAD

**Issue by evermeer** [ennioma/arek#45]
If permissions where denied and the user still clicks on the permission to enable it, then you could ask if the user wants to go to the settings to change the permissions. You could then do a quick open of the settings app using:

            UIApplication.shared.openURL(URL(string: UIApplicationOpenSettingsURLString)!)

**Comment by evermeer** [comment]
Ah, I see this is already supported. Sorry for asking. 
But then, could you add the configuration to the protocol so that I could do something like:
`        for var p in permissions { p.configuration.frequency = .Always }
`

**Comment by ennioma** [comment]
Exactly!

It already works in this way.

Let me think about the protocol in the meanwhile.
