### ISSUE TITLE
feature request:  i18n

### ISSUE THREAD

**Issue by muescha** [ennioma/arek#55]
feature request:  i18n

**Comment by evermeer** [comment]
You can use your own texts when you init the Arek objects with specifying the ArekPopupData

**Comment by muescha** [comment]
No. There are some more places where this is possible

**Comment by muescha** [comment]
https://github.com/ennioma/arek/blob/master/arek/Classes/Core/Arek.swift#L79

https://github.com/ennioma/arek/blob/master/arek/Classes/Core/Arek.swift#L84

**Comment by ennioma** [comment]
Yep,
I planned to move every plain string to a localized one.

**Comment by ennioma** [comment]
Hi @muescha, @evermeer,
I've partially fixed this with the release [1.2.1](https://github.com/ennioma/arek/tree/1.2.1).

There are still a couple of string not localized but I'll complete the job in 1.2.2. 

In the meanwhile I let this issue opened.
