### ISSUE TITLE
IOS10 Minimum Podspec

### ISSUE THREAD

**Issue by thewhitewood** [ennioma/arek#7]
Just checking if there's any reason why it needs to be IOS10 minimum on the pod-spec, can't it be 9+ ?

**Comment by ennioma** [comment]
Hi,
there are a couple of calls to methods only iOS 10+.  I'll push (I hope tonight) a new version where I'll manage these methods in order to support iOS 9+. (plus fixing a crash in the core 😊)

**Comment by ennioma** [comment]
Hi @thewhitewood,
I've released the tag _**0.0.4**_ that supports iOS9. 

https://github.com/ennioma/arek/tree/0.0.4 

Also I've submitted it to Cocoapods, so it should be available there soon.

Thanks!
