### ISSUE TITLE
How to adjust configuration values?

### ISSUE THREAD

**Issue by cpromise** [ennioma/arek#77]
Hello, arek people. Thanks for the great open source.

I'm trying to adjust the value of configuration declared in ArekBasePermission.
But when I access to configuration property in my project, compile error took place asserting this message. " 'configuration' is inaccessible due to its internal protection level"

Is there anyway to modify configuration of permission objects not by modify code in Arek.swift directly?

P.S. I'm not a native English speaker. So I'm not sure my issue report delivers the issue I experienced.

**Comment by ennioma** [comment]
Hi @cpromise,
Yes you should inject the configuration using the permission init as you can see here:

https://github.com/ennioma/arek/blob/master/code/Classes/Core/Arek.swift#L56-L60

I've created a gist for you: https://gist.github.com/ennioma/b8149594ea143a8b501c76bec4e9df31

Let me know if this is the case you were referring to.

Cheers

**Comment by cpromise** [comment]
After checking your comment, I found that I was working with 1.0 version.
It was my fault.
The gist you gave me and 'pod update' solved my problem.
Thank you.
Let me close this issue.

**Comment by ennioma** [comment]
No problem!

Glad you're able to configure permissions now.
