### ISSUE TITLE
[Notification] Should I call UIApplication.shared.registerForRemoteNotifications() by myself?

### ISSUE THREAD

**Issue by cpromise** [ennioma/arek#79]
When I try to register notification through the code below
```open func askForPermission(completion: @escaping ArekPermissionResponse) (ArekNotifications.swift:60)```

On iOS10, I cannot get device token while I can on iOS9.
I guess it is because ```UIApplication.shared.registerForRemoteNotifications()``` is not called on iOS10.
Am I right or missing something?

I'm using v.1.3.0.
Thank you for reading.

**Comment by ennioma** [comment]
Hi @cpromise,
Thank you! I've noticed that for iOS 10 I forgot to call that method if the operation is granted.

Tonight I'll release a new version. Thanks!

**Comment by cpromise** [comment]
Thank you for your guide.
Let me close this issue. 👍

**Comment by ennioma** [comment]
@cpromise This fix has been included in #80 which has been shipped with [v 1.3.1](https://github.com/ennioma/arek/releases/tag/1.3.1)
