### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by ajaysinghthakur** [ennioma/arek#85]
would want to see a sample project.

**Comment by ennioma** [comment]
Ok it's reasonable. I'm going to restore that soon

**Comment by ennioma** [comment]
@ajaysinghthakur I've created a sample project that you can find [here](https://github.com/ennioma/arek/tree/master/Example).

I've also released 1.4.1 (#86) with some minor refactoring.

**Comment by ajaysinghthakur** [comment]
thanks
